---
title: "Public Speaking"

---

Passionate about the sharing and application of research, I continue to regularly engage with the public to bring to live recent findings surrounding Psychology and wellbeing, especially mindfulness.

### Science Communication

I am continuously fascinated by science and its potential to be applied in our daily lives. Through this, I am passionate about bringing science out of the lab and into the streets, entertaining, educating and enthusing.

#### Guest Speaker and Lecturer
I have previously spoken as a guest speaker at an undergraduate Positive Psychology course elective at the University of Glasgow, sharing my own experience with mindfulness as well as exploring the science and current developments in this active and interesting field. I introduced discussion points to tie in with course topics and lead a group meditation exercise.

#### Podcast Guest Host

Recently, I had the pleasure of being a guest on the Glasgow University Psychology Society's monthly podcast, 'Psych Soc O'Clock', to talk about the field of behaviour change and habit formation.
In this podcast, I shared my research experience in this field, disseminating results of my own and others' research in an informal, entertaining and accessible way.

Audio to come - please check back later!


### Mindfulness

#### Mindfulness Taster Session

I have been an invited guest speaker for a Glasgow charity, introducing volunteers to mindfulness, some of the science behind it and guiding them through basic practices.


#### Introductory Mindfulness Workshops
In addition to smaller taster sessions, I also run workshops on mindfulness.

Aimed at individuals with little or no previous experience, in this workshop, I introduce participants to mindfulness in a simple way, demystifying the topic and sheading light on misconceptions. Some exploration of the science behind mindfulness is included to demonstrate the range of effects that mindfulness has been found to carry. With the aid of videos and discussion throughout, participants will learn about various forms of mindfulness practice and have the opportunity to join in four different mindfulness exercises. After each exercise, participants are encouraged to share their experiences in small groups and reflect on how they could apply their new skills in mindfulness within various aspects of their daily lives.

This workshop is popular with university students!

Previous workshops have taken place at the University of Glasgow with great success.

Photos to be uploaded soon - please check back later!


#### Advanced Mindfulness Workshops
Currently underdevelopment, I am keen to provide a workshop aimed at those who have prior experience in mindfulness or have completed the Introductory Mindfulness workshop.

In this, we will explore ways to overcome typical hurdles in mindfulness practice and consider new ways of integrating mindfulness skills into our daily lives.


### Inquiries
If you have any questions or would like to book a speaking event or workshop, please get in touch!
